In [2]:
import torch
X = torch.arange(16).reshape(4,4)
print(X)
# tensor([[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11],
#         [12, 13, 14, 15]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [5]:
print(X[-1])
print(X[1:3])

tensor([12, 13, 14, 15])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
Y=torch.arange(24).reshape(4,3,2)
print(Y[-1])
print(Y[1:3])

tensor([[18, 19],
        [20, 21],
        [22, 23]])
tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])
