# Scalar operation

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# Tensors

Tensors
While you can go far in your machine learning journey with only scalars, vectors, and matrices, eventually you may need to work with higher-order [tensors]. Tensors (give us a generic way of describing extensions to  nth -order arrays.) We call software objects of the tensor class "tensors" precisely because they too can have arbitrary numbers of axes. While it may be confusing to use the word tensor for both the mathematical object and its realization in code, our meaning should usually be clear from context. We denote general tensors by capital letters with a special font face (e.g.,  X ,  Y , and  Z ) and their indexing mechanism (e.g.,  xijk  and  [X]1,2i−1,3 ) follows naturally from that of matrices.

Tensors will become more important when we start working with images. Each image arrives as a  3rd -order tensor with axes corresponding to the height, width, and channel. At each spatial location, the intensities of each color (red, green, and blue) are stacked along the channel. Furthermore, a collection of images is represented in code by a  4th -order tensor, where distinct images are indexed along the first axis. Higher-order tensors are constructed, as were vectors and matrices, by growing the number of shape components.

In [3]:
image_sizes = 20*20*3
image_tensor = torch.arange(image_sizes).reshape(3, 20, 20)
image_red = image_tensor[0]
image_red.shape

torch.Size([20, 20])

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [5]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [6]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [7]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [8]:

(A.shape,
 A.sum(axis=0), #sum by column (along the axis 0 which is the row)
 A.sum(axis=0).shape, #
 A.sum(axis=1), #sum by row
 A.sum(axis=1).shape)

(torch.Size([2, 3]),
 tensor([3., 5., 7.]),
 torch.Size([3]),
 tensor([ 3., 12.]),
 torch.Size([2]))

In [9]:
A = torch.arange(24).reshape(2, 3, 4)
B = torch.arange(12).reshape(3, 4)

A + B  # B is broadcast to (2, 3, 4)
A, B, A+B

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]))

In [1]:
import torch
x = torch.arange(3, dtype = torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [1]:
import torch
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
x = torch.arange(3, dtype=torch.float32)

A, x, A@x, torch.mv(A, x).shape


(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 tensor([ 5., 14.]),
 torch.Size([2]))

In [3]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = torch.arange(12, dtype=torch.float32).reshape(3, 4)
C = torch.mm(A,B)

A,B,C,C.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[20., 23., 26., 29.],
         [56., 68., 80., 92.]]),
 torch.Size([2, 4]))

In [1]:
import torch
A = torch.arange(12).reshape(3, 4)
B = A.T

(A.T).T == A


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [1]:
import torch
A = torch.arange(12).reshape(3, 4)
B = torch.arange(start=13,end=25).reshape(3,4)


C = A.T + B.T
D = (A + B).T
C == D

len(A)
len(torch.arange(2))
A / A.sum(axis=0)

tensor([[0.0000, 0.0667, 0.1111, 0.1429],
        [0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6000, 0.5556, 0.5238]])